### ISSUE TITLE
Add CSS link in HTML

### ISSUE THREAD

**Issue by StefanyVasc** [StefanyVasc/doctor-care#19]
- style.css (pay attention to which file should be used)

- Tip:
`<link rel="stylesheet" type="text/css" href="Path to your file" />`

**Comment by prakhartiwari0** [comment]
Hey can I work on this issue?

**Comment by StefanyVasc** [comment]
> Hey can I work on this issue?

@prakhartiwari0 this issue has already been picked up by someone else. 



> where is your Main Html file??

@theavitw inside the src folder.
